-- Replica (simplificada) de las tablas de ExpresoFastC5K023_II2026 que usa el backend.
CREATE TABLE Conductor (
    conductor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre       VARCHAR(50) NOT NULL,
    apellidos    VARCHAR(50) NOT NULL,
    licencia     VARCHAR(20) NOT NULL UNIQUE,
    telefono     VARCHAR(20) NOT NULL,
    activo       BIT NOT NULL DEFAULT 1
);

CREATE TABLE Vehiculo (
    vehiculo_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa                 VARCHAR(15) NOT NULL UNIQUE,
    capacidad_kg          DECIMAL(10,2) NOT NULL,
    estado                VARCHAR(20) NOT NULL,
    empresa_id            INT NULL,
    conductor_asignado_id INT NULL
);

CREATE TABLE Envio (
    envio_id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_rastreo         VARCHAR(30) NOT NULL UNIQUE,
    direccion_destino      VARCHAR(200) NOT NULL,
    peso_kg                DECIMAL(10,2) NOT NULL,
    costo                  DECIMAL(10,2) NOT NULL,
    estado_envio           VARCHAR(20) NOT NULL,
    vehiculo_id            INT NOT NULL REFERENCES Vehiculo (vehiculo_id),
    conductor_id           INT NOT NULL REFERENCES Conductor (conductor_id),
    fecha_creacion         DATETIME NULL,
    fecha_modificacion     DATETIME NULL,
    destinatario           VARCHAR(150) NULL,
    fecha_despacho         DATE NULL,
    fecha_entrega_estimada DATE NULL,
    CONSTRAINT CK_Envio_Fechas CHECK (fecha_entrega_estimada IS NULL OR fecha_despacho IS NULL
                                      OR fecha_entrega_estimada > fecha_despacho)
);

-- Igual que database/lab11_paquetes.sql
CREATE TABLE PAQUETES (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    envio_id    INT NOT NULL,
    descripcion VARCHAR(255) NOT NULL,
    peso_kg     DECIMAL(5,2) NOT NULL,
    CONSTRAINT FK_Paquetes_Envios FOREIGN KEY (envio_id) REFERENCES Envio (envio_id) ON DELETE CASCADE
);
