USE [master]
GO
/****** Objeto: Database [ExpresoFastC5K023_II2026] Fecha de script: 2/10/2026 23:05:32 ******/
CREATE DATABASE [ExpresoFastC5K023_II2026]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ExpresoFastC5K023_II2026', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\ExpresoFastC5K023_II2026.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ExpresoFastC5K023_II2026_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\ExpresoFastC5K023_II2026_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ExpresoFastC5K023_II2026].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET ARITHABORT OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET  MULTI_USER 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET QUERY_STORE = ON
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [ExpresoFastC5K023_II2026]
GO
/****** Objeto: Table [dbo].[BitacoraEnvio] Fecha de script: 2/10/2026 23:05:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BitacoraEnvio](
	[bitacora_id] [int] IDENTITY(1,1) NOT NULL,
	[envio_id] [int] NOT NULL,
	[estado_anterior] [varchar](20) NOT NULL,
	[estado_nuevo] [varchar](20) NOT NULL,
	[fecha_cambio] [datetime] NOT NULL,
	[usuario_id] [int] NOT NULL,
	[observaciones] [varchar](250) NULL,
PRIMARY KEY CLUSTERED 
(
	[bitacora_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Conductor] Fecha de script: 2/10/2026 23:05:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Conductor](
	[conductor_id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[apellidos] [varchar](50) NOT NULL,
	[licencia] [varchar](20) NOT NULL,
	[telefono] [varchar](20) NOT NULL,
	[activo] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[conductor_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[licencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[EmpresaLogistica] Fecha de script: 2/10/2026 23:05:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EmpresaLogistica](
	[empresa_id] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](100) NOT NULL,
	[cedula_juridica] [varchar](20) NOT NULL,
	[telefono] [varchar](20) NOT NULL,
	[fecha_registro] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[empresa_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[nombre] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[cedula_juridica] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Envio] Fecha de script: 2/10/2026 23:05:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Envio](
	[envio_id] [int] IDENTITY(1,1) NOT NULL,
	[codigo_rastreo] [varchar](30) NOT NULL,
	[direccion_destino] [varchar](200) NOT NULL,
	[peso_kg] [decimal](10, 2) NOT NULL,
	[costo] [decimal](10, 2) NOT NULL,
	[estado_envio] [varchar](20) NOT NULL,
	[vehiculo_id] [int] NOT NULL,
	[conductor_id] [int] NOT NULL,
	[fecha_creacion] [datetime] NULL,
	[fecha_modificacion] [datetime] NULL,
	[destinatario] [varchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[envio_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[codigo_rastreo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Rol] Fecha de script: 2/10/2026 23:05:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rol](
	[rol_id] [int] IDENTITY(1,1) NOT NULL,
	[nombre_rol] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[rol_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[nombre_rol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Usuario] Fecha de script: 2/10/2026 23:05:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuario](
	[usuario_id] [int] IDENTITY(1,1) NOT NULL,
	[username] [varchar](50) NOT NULL,
	[password_hash] [varchar](255) NOT NULL,
	[nombre_completo] [varchar](100) NOT NULL,
	[email] [varchar](100) NOT NULL,
	[activo] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[usuario_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[UsuarioRol] Fecha de script: 2/10/2026 23:05:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsuarioRol](
	[usuario_id] [int] NOT NULL,
	[rol_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[usuario_id] ASC,
	[rol_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[Vehiculo] Fecha de script: 2/10/2026 23:05:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vehiculo](
	[vehiculo_id] [int] IDENTITY(1,1) NOT NULL,
	[placa] [varchar](15) NOT NULL,
	[capacidad_kg] [decimal](10, 2) NOT NULL,
	[estado] [varchar](20) NOT NULL,
	[empresa_id] [int] NOT NULL,
	[conductor_asignado_id] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[vehiculo_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[placa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Conductor] ADD  CONSTRAINT [DF_Conductor_activo]  DEFAULT ((1)) FOR [activo]
GO
ALTER TABLE [dbo].[BitacoraEnvio]  WITH CHECK ADD  CONSTRAINT [FK_Bitacora_Envio] FOREIGN KEY([envio_id])
REFERENCES [dbo].[Envio] ([envio_id])
GO
ALTER TABLE [dbo].[BitacoraEnvio] CHECK CONSTRAINT [FK_Bitacora_Envio]
GO
ALTER TABLE [dbo].[BitacoraEnvio]  WITH CHECK ADD  CONSTRAINT [FK_Bitacora_Usuario] FOREIGN KEY([usuario_id])
REFERENCES [dbo].[Usuario] ([usuario_id])
GO
ALTER TABLE [dbo].[BitacoraEnvio] CHECK CONSTRAINT [FK_Bitacora_Usuario]
GO
ALTER TABLE [dbo].[Envio]  WITH CHECK ADD  CONSTRAINT [FK_Envio_Conductor] FOREIGN KEY([conductor_id])
REFERENCES [dbo].[Conductor] ([conductor_id])
GO
ALTER TABLE [dbo].[Envio] CHECK CONSTRAINT [FK_Envio_Conductor]
GO
ALTER TABLE [dbo].[Envio]  WITH CHECK ADD  CONSTRAINT [FK_Envio_Vehiculo] FOREIGN KEY([vehiculo_id])
REFERENCES [dbo].[Vehiculo] ([vehiculo_id])
GO
ALTER TABLE [dbo].[Envio] CHECK CONSTRAINT [FK_Envio_Vehiculo]
GO
ALTER TABLE [dbo].[UsuarioRol]  WITH CHECK ADD  CONSTRAINT [FK_UsuarioRol_Rol] FOREIGN KEY([rol_id])
REFERENCES [dbo].[Rol] ([rol_id])
GO
ALTER TABLE [dbo].[UsuarioRol] CHECK CONSTRAINT [FK_UsuarioRol_Rol]
GO
ALTER TABLE [dbo].[UsuarioRol]  WITH CHECK ADD  CONSTRAINT [FK_UsuarioRol_Usuario] FOREIGN KEY([usuario_id])
REFERENCES [dbo].[Usuario] ([usuario_id])
GO
ALTER TABLE [dbo].[UsuarioRol] CHECK CONSTRAINT [FK_UsuarioRol_Usuario]
GO
ALTER TABLE [dbo].[Vehiculo]  WITH CHECK ADD  CONSTRAINT [FK_Vehiculo_ConductorAsignado] FOREIGN KEY([conductor_asignado_id])
REFERENCES [dbo].[Conductor] ([conductor_id])
GO
ALTER TABLE [dbo].[Vehiculo] CHECK CONSTRAINT [FK_Vehiculo_ConductorAsignado]
GO
ALTER TABLE [dbo].[Vehiculo]  WITH CHECK ADD  CONSTRAINT [FK_Vehiculo_Empresa] FOREIGN KEY([empresa_id])
REFERENCES [dbo].[EmpresaLogistica] ([empresa_id])
GO
ALTER TABLE [dbo].[Vehiculo] CHECK CONSTRAINT [FK_Vehiculo_Empresa]
GO
ALTER TABLE [dbo].[Envio]  WITH CHECK ADD CHECK  (([estado_envio]='CANCELADO' OR [estado_envio]='ENTREGADO' OR [estado_envio]='EN_TRANSITO' OR [estado_envio]='PENDIENTE'))
GO
ALTER TABLE [dbo].[Rol]  WITH CHECK ADD CHECK  (([nombre_rol]='ROLE_CONDUCTOR' OR [nombre_rol]='ROLE_OPERADOR' OR [nombre_rol]='ROLE_ADMIN'))
GO
ALTER TABLE [dbo].[Vehiculo]  WITH CHECK ADD CHECK  (([estado]='MANTENIMIENTO' OR [estado]='EN_RUTA' OR [estado]='DISPONIBLE'))
GO
/****** Objeto: StoredProcedure [dbo].[SP_OBTENER_ENVIOS_POR_ESTADO] Fecha de script: 2/10/2026 23:05:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_OBTENER_ENVIOS_POR_ESTADO]
    @pEstado VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        envio_id,
        codigo_rastreo,
        destinatario,
        direccion_destino,
        peso_kg,
        costo,
        estado_envio,
        vehiculo_id,
        conductor_id,
        fecha_creacion,
        fecha_modificacion
    FROM dbo.Envio
    WHERE estado_envio = @pEstado
    ORDER BY fecha_creacion DESC;
END
GO
/****** Objeto: StoredProcedure [dbo].[SP_RESUMEN_METRICAS_ENVIOS] Fecha de script: 2/10/2026 23:05:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_RESUMEN_METRICAS_ENVIOS]
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        estado_envio,
        COUNT(*)   AS total_envios,
        SUM(costo) AS costo_total
    FROM dbo.Envio
    GROUP BY estado_envio;
END
GO
USE [master]
GO
ALTER DATABASE [ExpresoFastC5K023_II2026] SET  READ_WRITE 
GO
